name: localchat

on:
  push:
    branches:
      - master
jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Linux Binary
        run: wails build -devtools
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: ./build/bin/localchat

  setup-go-windows:
    needs: setup-go
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Windows Binary
        run: wails build -devtools
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ./build/bin/localchat.exe
